# Meeting Notes 11-5

1. Michelle used Git!
  * Sorry, Grandma
2. [SassSquatch][1]
  * Pull requess and collaboration welcome!
  * Discussion of the sass function to strip out units (for rem/pixel usage)
  * CSS3 mixins need testing (skews/transforms)
  * Grids.scss
     Hate descriptor elements (eg col1, col-one-third), use includes for a solution
     Semantic classes
     Requires people to edit sass because they're not exposed
     We are pushing sass use, 
     Index file
3. Our Website
  * We need content
  * Blog template
4. Modular Content
  * Person/Directory
  * Events Calendar
  * Similar plugins with matching CSS
  * Talking about setup of theme: support gravity forms or other plugins and teach people how to turn them off
  * On addressing verticals: build up a library of the "extra 5%"
  * Value-add: in plugins
  * Theme is more like _s but also immediately usable (not quite so minimalist), more like Justin Tadlock's [Hybrid][2]
  * "Front end framework using the WordPress theming engine"
5. Theme and Admin Control with Sass
  * Coming later
  * No "theme options"
6. On the use of sass
  * Right vs. easy, people will always pick easy
  * Preferred to support sass, BUT will have a base set of classes generated by mixins
  * Write the code so that there is a variable for grid columns, etc.
6. Action Items
  * Wireframes for verticals
  * Sass mixins and testing
  * Which plugins do we want to support?
  * Put up a website

  Side note: Editorial.ly push to WordPress feature
  Codepen for collaborative coding


[1]: https://github.com/3themes/sassquatch
[2]: https://github.com/justintadlock/hybrid-core
